# React frontend Dockerfile for development
FROM node:20-alpine

WORKDIR /app

# Install curl
RUN apk add --no-cache curl

# Copy package.json
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files to the working directory
COPY . .

ENV DOCKER_ENV=True

EXPOSE 3000

# Start the application in development mode
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
