# Generated by Django 5.1.1 on 2024-09-08 10:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=400), size=None)),
                ('instructions', models.TextField(max_length=1000)),
                ('image_name', models.TextField(max_length=200)),
                ('cleaned_ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=400), size=None)),
            ],
        ),
    ]
