# Generated by Django 5.1.1 on 2024-09-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipify_core', '0002_alter_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
