# Generated by Django 5.1.1 on 2024-10-06 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipify_core', '0003_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
